# permissions for end users to view testoperatordocs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testoperatordocs-viewer-role
rules:
- apiGroups:
  - akshay.akshay
  resources:
  - testoperatordocs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - akshay.akshay
  resources:
  - testoperatordocs/status
  verbs:
  - get
