name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
      
    - name: install the crd ref docs binary
      run: | 
          go get -u github.com/ibakshay/crd-ref-docs@v1.1.1
          go get k8s.io/apimachinery/pkg/apis/meta/v1@v0.22.4
          go get k8s.io/apimachinery/pkg/runtime/schema@v0.22.4
      
    - name: print GO Path
      run: |
        go env GOPATH
        
    - name: CD into the Go Path and list all the binaries inside
      run: |
        cd $(go env GOPATH)/bin
        ls
    - name: generate doc for the operator
      run: |
        crd-ref-docs \
        --source-path=./api \
        --config=config.yaml \
        --renderer=markdown \
        --templates-dir=templates/markdown \
        --output-path=./docs
        
    - name: list the source code
      run: |
        ls 
    - name: Commit and push the new generated file
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        add: '*.md --force'
        
